# From IvanUkhov/.development
# Helper functions
function has {
  if type "${1}" > /dev/null; then
    return 0
  else
    return 1
  fi
}

function is {
  if [[ "$(echo $(uname) | tr '[:upper:]' '[:lower:]')" == "${1}" ]]; then
    return 0
  else
    return 1
  fi
}

#############################################
# Themes and plugins
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git web-search zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

#############################################
# My custom aliases

alias setup="cd ~/.setup"
alias config="code ~/.zshrc"

# LLM related aliases
q() {
  { echo "$@"; cat; } | interpreter --model gpt-4 -y -s "Just reply with the answer, dont list your thought process"
}

llm() {
  { echo "$@"; cat; } | interpreter --model gpt-3.5-turbo -y
}

llm-safe() {
  { echo "$@"; cat; } | interpreter --model gpt-3.5-turbo
}

# Azure related aliases
listcontainers() {
    az storage container list --account-name "$1" --query "[].name" -o table
}


#############################################

# From IvanUkhov/.development with some modifications
# Git aliases
if has git; then
  alias g=git
  alias ga='git add'
  alias gap='git add --patch'
  alias gb='git branch'
  alias gc='git commit'
  alias gca='git commit --amend'
  alias gcane='git commit --amend --no-edit'
  alias gco='git checkout'
  alias gd='git diff'
  alias gds='git diff --staged'
  alias gg='git grep --line-number'
  alias gl='git log'
  alias gp='git push'
  alias gpl='git pull'
  alias gs='git status'
fi

# GitHub CLI aliases
if has gh; then
  alias gho='gh browse'
  alias ghpr='gh pr view --web'
fi

#############################################

# Load Secrets
if [[ -f ~/.secrets ]]; then
  source ~/.secrets
fi

#############################################
